<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\yildiz.DataAccess\yildiz.DataAccess.csproj" />
    <ProjectReference Include="..\yildiz.entities\yildiz.entities.csproj" />
  </ItemGroup>

</Project>
